### ISSUE TITLE
Missing IPv6 support

### ISSUE THREAD

**Issue by zaccone** [volumio/RootFS#1]
Hi,

I noticed that Volumio player has IPv6 disabled by default.
My home network does support IPv6 and all new devices pick it up correctly, yet not Volumio.
In my opinion it would be good to support IPv6 in the future releases.

**Comment by timstpierre** [comment]
I'm going to call this an actual problem.  It's 2017, and any kind of device without IPv6 support will have a short lifespan.  Our network is mostly IPv6, with many services not available on V4.  I had to go and create a bunch of special rules on the NFS server just to accommodate the volumio lack of IPv6 support, since we don't normally use V4 anymore.

I'm happy to help with this, as long as I can have a little help rolling the changes back into the package.
